### ISSUE TITLE
Consider adding support for discord

### ISSUE THREAD

**Issue by RadicalZephyr** [reillysiemens/layabout#18]
I want to use the Layabout API with all the chat services.  It's so good!

**Comment by reillysiemens** [comment]
@RadicalZephyr: I'm really glad you like the API so much. Layabout 1.x is pretty tightly coupled to Slack, but with a little work the abstraction could be more generic and support other things like Discord or [Matrix](https://matrix.org/blog/home/). I think the right way to handle that would be to force the user to bring their own client for whatever service they were interacting with. At that point Layabout would just be a *very* thin event-handling wrapper. I'm not opposed to that idea, but it's not something I think can be done without a 2.x release.

**Comment by reillysiemens** [comment]
FWIW, as Layabout has _just_ been released I have no timeline for when, if at all, a change this big would actually be introduced, but I'll create a 2.0 milestone and add this issue to it.

**Comment by reillysiemens** [comment]
@RadicalZephyr: Have you seen [Rapptz/discord.py](https://github.com/Rapptz/discord.py)? At a glance it looks like it has all the event-driven goodness *and* it uses `async`. Given that that library exists I think I'm unlikely to pursue Discord support for Layabout, though I'm still open to being convinced otherwise.

**Comment by reillysiemens** [comment]
[Rapptz/discord.py](https://github.com/Rapptz/discord.py) is just a much better library for Discord and doesn't really mesh with the design here. I won't be pursuing Discord support for this library.
