### ISSUE TITLE
Simple example should fail gracefully and informatively when Slack API token is not present

### ISSUE THREAD

**Issue by SophieKAn** [reillysiemens/layabout#23]
I attempted to run the simple example without having a Slack API token. Having never used `layabout` or the Slack RTM API, I didn't know I needed one. This exception should be handled more gracefully and tell the user that a token is needed and possibly where/how to get it. This would be helpful for people whose first experience with Slack APIs is `layabout`.

```
(layabout) sophie@leaflet:~/layabout/examples/simple$ pipenv run example
Printing all events. Press Ctrl-C to quit.

Traceback (most recent call last):
  File "example.py", line 17, in <module>
    app.run()
  File "/home/sophie/layabout/layabout.py", line 230, in run
    backoff=backoff
  File "/home/sophie/layabout/layabout.py", line 181, in _ensure_slack
    slack: SlackClient = _create_slack(connector)
  File "/home/sophie/.virtualenvs/layabout/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/sophie/layabout/layabout.py", line 296, in _create_slack_with_env_var
    raise MissingToken(f"Could not acquire token from {env_var}")
layabout.MissingToken: Could not acquire token from LAYABOUT_TOKEN
```

**Comment by reillysiemens** [comment]
Good catch, @SophieKAn! If you feel comfortable submitting the change yourself you should be able to fix this by wrapping the `app.run()` call in an exception block like

```python
from layabout import Layabout, MissingToken

# ...

try:
    app.run()
except MissingToken:
    print('Some message about how to deal with tokens')
```

As for acquiring a token, [this Slack documentation](https://api.slack.com/docs/token-types#bot) should help.
