### ISSUE TITLE
Consider an alternative to setup.py

### ISSUE THREAD

**Issue by reillysiemens** [reillysiemens/layabout#6]
[`Pipfile`](https://github.com/pypa/pipfile) (and its counterpart `Pipfile.lock`) are a new way of declaring Python project metadata. They aren't currently respected by `pip` proper, but they're fast-tracked to be included in the near future and they're respected by the [`pipenv`](https://github.com/pypa/pipenv), which looks like a great alternative to the typical dev process using `virtualenvwrapper`.

**Comment by reillysiemens** [comment]
Reflecting on the research @RadicalZephyr did in #7 I've decided to ignore pipenv and `Pipfile` as enhancements for now, but may re-evaluate this decision later.

**Comment by RadicalZephyr** [comment]
@reillysiemens  [This article](https://realpython.com/pipenv-guide/#package-distribution) is an interesting suggestion for a `setup.py` + `pipenv` workflow.  May be worth re-evaluating.  In addition to this, I think the dev dependencies you use could and maybe should be listed in the Pipfile then.

That way, you get the correct non-hacky `setup.py` distribution, and then a nice dev experience by using pipenv.  I'm going to try it out on a new python lib I'm working on, I'll let you know how it goes.

Edit: just saw that I forgot to include the link!

**Comment by reillysiemens** [comment]
@RadicalZephyr: I'd be interested to hear how your experience goes and will probably base my decision on that. I'd like to have ideas from someone else's experience and my own experiments before actually committing a `Pipfile` to the repo.

**Comment by reillysiemens** [comment]
I'll reopen the issue pending your comments though.

**Comment by reillysiemens** [comment]
Ehhh... I added some `Pipfile`s into the example applications because I think it makes it easier for newcomers to see what Layabout can do, but in doing so I ran in to **numerous** issues with `pipenv`. Right now the primary means of using a `Pipfile` is through `pipenv` and it doesn't add much for my personal development workflow just yet...

I'm keeping this issue open because the Python packaging ecosystem is in a state of flux right now and its worth revisiting this until the dust settles I think.

**Comment by rawrgulmuffins** [comment]
If you have the mental energy I'd love to know what the issues are. Let me just leech some knowledge from you.

**Comment by reillysiemens** [comment]
@rawrgulmuffins: I'm afraid I don't have the mental energy to enumerate them all here. I did, however, recently evaluate [`poetry`](https://poetry.eustace.io/) (and, by association, a `pyproject.toml` file), as an alternative to [`pipenv`](https://pipenv.readthedocs.io/en/latest/) and encountered many similar issues. I think that `poetry` is spiritually closer to what I want, but I don't think either is meeting my workflow right now.

Both `pipenv` and `poetry` are very young tools. I have an established workflow for shipping Python packages that "Just Works :tm:" and neither of them has succeeded (yet!) at making my workflow easier.

I will continue to keep this issue open, but given that `poetry` or some unknown future candiate might be a contender as well I'm going to change the title accordingly.

**Comment by SophieKAn** [comment]
I'll take a stab at getting this project set up with `poetry`!

**Comment by reillysiemens** [comment]
It's been a while since I revisited this issue, but I've worked more with `poetry` now and decided I like it, so that sounds good to me, @SophieKAn! :grin:
