### ISSUE TITLE
Can't install with pip 10

### ISSUE THREAD

**Issue by RadicalZephyr** [reillysiemens/layabout#8]
Seems related to this probably: [Pip 10 is coming, and will move all internal APIs](https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html)

In the `setup.py` file, there is an import from `pip.req` that fails.  I tried to naively solve this by defining a `parse_requirements` function as described [here](https://github.com/capless/warrant/issues/96) but it didn't work, I think because of the usage of the `-r` in dev and test requirements files.

**Comment by reillysiemens** [comment]
This should be resolved as of #13 as requirements files are no longer loaded from disk and `pip`'s internals aren't relied upon at all.
